language: php
php:
  - 7.1.9
env:
  - PHP_ENV=test CC_TEST_REPORTER_ID=bd2d51d6624952183f1d6c4e3f59b2d6cf499eea28cf7f0ef10e669230f127cc
before_script:
  - "composer require codeclimate/php-test-reporter --dev"
  - composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm install
  - npm run build
script:
  - bash test
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT